authScoreWeight: '0.1'
userIdentityWeight: '0.3'
contextScoreWeight: '0.25'
expScoreWeight: '0.15'
anomalyScoreWeight: '0.2'
adminThreshold: '0.6'
approverThreshold: '0.6'
securityViewerThreshold: '0.4'
signInSuccessRatioThreshold: '0.5'
highRiskLocations:
- ''
lowRiskLocations:
- 'Nairobi/KE'
mediumRiskLocations:
- 'Mombasa/KE'
- 'Kisumu/KE'

periodStartInput: 00:00:00
periodEndInput: 06:00:00

